/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#define RCC_BASE_REG					0X40023800UL
#define GPIO_A_BASE_REG					0X40020000UL

#define RCC_CFG_OFFSET					0X08UL
#define RCC_CFG_REG_ADDR				(RCC_BASE_REG + RCC_CFG_OFFSET)

#define RCC_AHB1_EN_OFFSET				0X30
#define RCC_AHB1_EN_REG_ADDR			(RCC_BASE_REG + RCC_AHB1_EN_OFFSET)

#define GPIO_PORT_A_MODE_OFFSET			0X00
#define GPIO_PORT_A_MODE_REG_ADDR		(GPIO_A_BASE_REG + GPIO_PORT_A_MODE_OFFSET)

#define GPIO_A_AF_TYPE_LO_OFFSET		0X20
#define GPIO_A_AF_TYPE_LO_REG_ADDR		(GPIO_A_BASE_REG + GPIO_A_AF_TYPE_LO_OFFSET)

#define GPIO_A_AF_TYPE_HI_OFFSET		0X24
#define GPIO_A_AF_TYPE_HI_REG_ADDR		(GPIO_A_BASE_REG + GPIO_A_AF_TYPE_HI_OFFSET)


int main(void)
{
	uint32_t *p_rcc_cfg_reg = (uint32_t*) RCC_CFG_REG_ADDR;
	uint32_t *p_rcc_ahb1_en_reg = (uint32_t*) RCC_AHB1_EN_REG_ADDR;
	uint32_t *p_gpio_a_mode_reg = (uint32_t*) GPIO_PORT_A_MODE_REG_ADDR;
	uint32_t *p_gpio_a_af_lo_reg = (uint32_t*) GPIO_A_AF_TYPE_LO_REG_ADDR;
	uint32_t *p_gpio_a_af_hi_reg = (uint32_t*) GPIO_A_AF_TYPE_HI_REG_ADDR;

	// Set the RCC CFG to Output the HSI Clock through MCO1
	// Set bit 21 and 22 to 0
	*p_rcc_cfg_reg &= (0xFF9FFFFF);

	// Enable the clock for AHB1 so that Port A is enabled
	// Set bit 1 to enable Port A
	*p_rcc_ahb1_en_reg |= (0x1);

	// Set Pin 8 to AF Mode by setting bits 16 and 17 to '10'
	*p_gpio_a_mode_reg &= (0xFFFCFFFF);
	*p_gpio_a_mode_reg |= (2 << 16);

	// Set Pin 8 AF Mode to Type 0
	// Set bits 0-3 to '0000'
	*p_gpio_a_af_hi_reg &= (0xFFFFFFF0);

    /* Loop forever */
	for(;;);
}
